### PR TITLE
prepare for Joomla 4

### PR DESCRIPTION
**Pull request by hans2103**
- replace addStylesheet by HTMLHelper::_('stylesheet'
- replace addScript by HTMLHelper::_('script'
- move conditional js file for lt IE9 to PHP code above
- move set Meta Data viewport to PHP code above
- add setHtml5 so Joomla . will add meta tag charset utf8
- remove obsolete code from HTML tag
- replace JUri, JText JHtml and JFactory with same Joomla 4 namespaced items. Works in J3 already.
- replace getParam sitename with Factory::getConfig

### CODE REVIEW

**Comment by jwiesel** [comment]
Hi @hans2103 ,
thanks for providing the pull-request. I've not been up-to-date about recent Joomla core developments. Are all of your changes compatible with Joomla 3? If so: Since which version? I'd like to keep a high level of compatibility and inform the users about the minimum Joomla version that is needed for the template (right now I guess it is Joomla! 3.0).

**Comment by hans2103** [comment]
most of it since Joomla 3.8.0 22 Sept 2017

- ```HTMLHelper::_('stylesheet'``` 
- ```HTMLHelper::_('script' ``` 
- ```setHtml5``` -> https://github.com/joomla/joomla-cms/blob/b141556de2355358976812b2d9ebce7952c23d4f/libraries/src/Document/HtmlDocument.php#L426

**Comment by Magnytu2** [comment]
Hello, I just happened to come across this project. I've been trying to make a bootstrap 4.5 or 5 template for Joomla 4 for several days. I'm not a developer and I'm lost. The grid layout is very complex for me when I watch the latest Cassiopeia.
The goal is to create a neutral template. With a very complete admin like ProtostarPlus for beginners who do not master the code. And to be able to use the bootstrap classes as much as possible.

**Comment by N6REJ** [comment]
@Magnytu2 it is in our latest beta

**Comment by N6REJ** [comment]
@hans2103 why close it?

**Comment by hans2103** [comment]
@N6REJ house cleaning on my open GitHub issues and PR.... and since my PR is open since October 2018 there seems to bee no interest merging it.

**Comment by Magnytu2** [comment]
@N6REJ @hans2103 @brianteeman Hello and thank you. How can I get this latest version. Because the one I got, doesn't work on Joomla 4 beta 6. I have to rename the html file. And the bootstrap menu with the sub menus does not work. Cassiopeia is very good. But not neutral enough for beginners who will want to use their logo in jpg., Who will want to apply their colors without coding. I know Joomla wants to leave the beginner world and focus on the A11Y. On the contrary, I am looking to bring Joomla closer to small users like me. This is why I am looking for a solid and neutral bootstrap 4 or 5 template base. Thank you very much.

**Comment by N6REJ** [comment]
Cassiopeia is the J4 template.  It was totally reworked for beta 6.
My brain just went blank.. ask in https://www.facebook.com/groups/joomlanospam I think they will have more info for you, especially considering this site is for bugs.

**Pull request closed without merging**
